export interface Vocabulary {
  id: number;
  categoryId: Category;
  englishWord: string;
  koreanWord: string;
  chineseWord: string;  // Add this line
}
  
  export enum Category {
    StandaloneWords = 1,
    L1P1,
    L1P2,
    L1P3,
    L1P4,
    L1P5,
    L1P6,
    L1P7,
    L1P8,
    L1P9,
    L1P10,
    L1P11,
    L1P12
  }
  
  export const vocabularyList: Vocabulary[] = [
    { id: 1, categoryId: Category.StandaloneWords, englishWord: 'Hello', koreanWord: '안녕하세요', chineseWord: '你好' },
    { id: 2, categoryId: Category.StandaloneWords, englishWord: 'Teeth', koreanWord: '이', chineseWord: '牙齿' },
    { id: 3, categoryId: Category.StandaloneWords, englishWord: 'Cucumber', koreanWord: '오이', chineseWord: '黄瓜' },
    { id: 4, categoryId: Category.StandaloneWords, englishWord: 'Man\'s younger brother', koreanWord: '아우', chineseWord: '弟弟' },
    { id: 5, categoryId: Category.StandaloneWords, englishWord: 'Kid', koreanWord: '아이', chineseWord: '孩子' },
    { id: 6, categoryId: Category.StandaloneWords, englishWord: 'Singer', koreanWord: '가수', chineseWord: '歌手' },
    { id: 7, categoryId: Category.StandaloneWords, englishWord: 'Meat', koreanWord: '고기', chineseWord: '肉' },
    { id: 8, categoryId: Category.StandaloneWords, englishWord: 'Shoe', koreanWord: '구두', chineseWord: '鞋' },
    { id: 9, categoryId: Category.StandaloneWords, englishWord: 'Country', koreanWord: '나라', chineseWord: '国家' },
    { id: 10, categoryId: Category.StandaloneWords, englishWord: 'Tree', koreanWord: '나무', chineseWord: '树' },
    { id: 11, categoryId: Category.StandaloneWords, englishWord: 'Leg', koreanWord: '다리', chineseWord: '腿' },
    { id: 12, categoryId: Category.StandaloneWords, englishWord: 'Radio', koreanWord: '라디오', chineseWord: '收音机' },
    { id: 13, categoryId: Category.StandaloneWords, englishWord: 'Hair', koreanWord: '머리', chineseWord: '头发' },
    { id: 14, categoryId: Category.StandaloneWords, englishWord: 'Banana', koreanWord: '바나나', chineseWord: '香蕉' },
    { id: 15, categoryId: Category.StandaloneWords, englishWord: 'Pants', koreanWord: '바지', chineseWord: '裤子' },
    { id: 16, categoryId: Category.StandaloneWords, englishWord: 'Cow', koreanWord: '소', chineseWord: '牛' },
    { id: 17, categoryId: Category.StandaloneWords, englishWord: 'Baby', koreanWord: '아기', chineseWord: '婴儿' },
    { id: 18, categoryId: Category.StandaloneWords, englishWord: 'Mother', koreanWord: '어머니', chineseWord: '母亲' },
    { id: 19, categoryId: Category.StandaloneWords, englishWord: 'Map', koreanWord: '지도', chineseWord: '地图' },
    { id: 20, categoryId: Category.StandaloneWords, englishWord: 'Hat', koreanWord: '모자', chineseWord: '帽子' },
    { id: 21, categoryId: Category.StandaloneWords, englishWord: 'Father (polite)', koreanWord: '아버지', chineseWord: '父亲' },
    { id: 22, categoryId: Category.StandaloneWords, englishWord: 'Waist', koreanWord: '허리', chineseWord: '腰' },
    { id: 23, categoryId: Category.StandaloneWords, englishWord: 'Baseball', koreanWord: '야구', chineseWord: '棒球' },
    { id: 24, categoryId: Category.StandaloneWords, englishWord: 'Palm Tree', koreanWord: '야자수', chineseWord: '棕榈树' },
    { id: 25, categoryId: Category.StandaloneWords, englishWord: 'Story', koreanWord: '이야기', chineseWord: '故事' },
    { id: 26, categoryId: Category.StandaloneWords, englishWord: 'Woman', koreanWord: '여자', chineseWord: '女人' },
    { id: 27, categoryId: Category.StandaloneWords, englishWord: 'Rice plant', koreanWord: '벼', chineseWord: '稻子' },
    { id: 28, categoryId: Category.StandaloneWords, englishWord: 'Tongue', koreanWord: '혀', chineseWord: '舌头' },
    { id: 29, categoryId: Category.StandaloneWords, englishWord: 'Yoga', koreanWord: '요가', chineseWord: '瑜伽' },
    { id: 30, categoryId: Category.StandaloneWords, englishWord: 'Cooking', koreanWord: '요리', chineseWord: '烹饪' },
    { id: 31, categoryId: Category.StandaloneWords, englishWord: 'Professor', koreanWord: '교수', chineseWord: '教授' },
    { id: 32, categoryId: Category.StandaloneWords, englishWord: 'Glass', koreanWord: '유리', chineseWord: '玻璃' },
    { id: 33, categoryId: Category.StandaloneWords, englishWord: 'Tissue', koreanWord: '휴지', chineseWord: '纸巾' },
    { id: 34, categoryId: Category.StandaloneWords, englishWord: 'Milk', koreanWord: '우유', chineseWord: '牛奶' },
    { id: 35, categoryId: Category.StandaloneWords, englishWord: 'Card', koreanWord: '카드', chineseWord: '卡片' },
    { id: 36, categoryId: Category.StandaloneWords, englishWord: 'Nose', koreanWord: '코', chineseWord: '鼻子' },
    { id: 37, categoryId: Category.StandaloneWords, englishWord: 'Height', koreanWord: '키', chineseWord: '身高' },
    { id: 38, categoryId: Category.StandaloneWords, englishWord: 'Ostrich', koreanWord: '타조', chineseWord: '鸵鸟' },
    { id: 39, categoryId: Category.StandaloneWords, englishWord: 'Tomato', koreanWord: '토마토', chineseWord: '番茄' },
    { id: 40, categoryId: Category.StandaloneWords, englishWord: 'Bull fighter', koreanWord: '투우사', chineseWord: '斗牛士' },
    { id: 41, categoryId: Category.StandaloneWords, englishWord: 'Fly (insect)', koreanWord: '파리', chineseWord: '苍蝇' },
    { id: 42, categoryId: Category.StandaloneWords, englishWord: 'Grape', koreanWord: '포도', chineseWord: '葡萄' },
    { id: 43, categoryId: Category.StandaloneWords, englishWord: 'Stamp', koreanWord: '우표', chineseWord: '邮票' },
    { id: 44, categoryId: Category.StandaloneWords, englishWord: 'Tea', koreanWord: '차', chineseWord: '茶' },
    { id: 45, categoryId: Category.StandaloneWords, englishWord: 'Skirt', koreanWord: '치마', chineseWord: '裙子' },
    { id: 46, categoryId: Category.StandaloneWords, englishWord: 'Pepper', koreanWord: '고추', chineseWord: '辣椒' },
    { id: 47, categoryId: Category.StandaloneWords, englishWord: 'Coffee', koreanWord: '커피', chineseWord: '咖啡' },
    { id: 48, categoryId: Category.StandaloneWords, englishWord: 'Coat', koreanWord: '코트', chineseWord: '外套' },
    { id: 49, categoryId: Category.StandaloneWords, englishWord: 'Train ticket', koreanWord: '기차표', chineseWord: '火车票' },
    { id: 50, categoryId: Category.StandaloneWords, englishWord: 'Magpie', koreanWord: '까치', chineseWord: '喜鹊' },
    { id: 51, categoryId: Category.StandaloneWords, englishWord: 'Tail', koreanWord: '꼬리', chineseWord: '尾巴' },
    { id: 52, categoryId: Category.StandaloneWords, englishWord: 'Elephant', koreanWord: '코끼리', chineseWord: '大象' },
    { id: 53, categoryId: Category.StandaloneWords, englishWord: 'Pick (fruit)', koreanWord: '따다', chineseWord: '摘' },
    { id: 54, categoryId: Category.StandaloneWords, englishWord: 'Float', koreanWord: '뜨다', chineseWord: '漂浮' },
    { id: 55, categoryId: Category.StandaloneWords, englishWord: 'Headband', koreanWord: '머리띠', chineseWord: '发带' },
    { id: 56, categoryId: Category.StandaloneWords, englishWord: 'Root', koreanWord: '뿌리', chineseWord: '根' },
    { id: 57, categoryId: Category.StandaloneWords, englishWord: 'Bones', koreanWord: '뼈', chineseWord: '骨头' },
    { id: 58, categoryId: Category.StandaloneWords, englishWord: 'Father (casual)', koreanWord: '아빠', chineseWord: '爸爸' },
    { id: 59, categoryId: Category.StandaloneWords, englishWord: 'Cheap', koreanWord: '싸다', chineseWord: '便宜' },
    { id: 60, categoryId: Category.StandaloneWords, englishWord: 'Write', koreanWord: '쓰다', chineseWord: '写' },
    { id: 61, categoryId: Category.StandaloneWords, englishWord: 'Middle-aged man', koreanWord: '아저씨', chineseWord: '大叔' },
    { id: 62, categoryId: Category.StandaloneWords, englishWord: 'Steam', koreanWord: '찌다', chineseWord: '蒸' },
    { id: 63, categoryId: Category.StandaloneWords, englishWord: 'Fake', koreanWord: '가짜', chineseWord: '假的' },
    { id: 64, categoryId: Category.StandaloneWords, englishWord: 'Ant', koreanWord: '개미', chineseWord: '蚂蚁' },
    { id: 65, categoryId: Category.StandaloneWords, englishWord: 'Ship', koreanWord: '배', chineseWord: '船' },
    { id: 66, categoryId: Category.StandaloneWords, englishWord: 'Bird', koreanWord: '새', chineseWord: '鸟' },
    { id: 67, categoryId: Category.StandaloneWords, englishWord: 'Sun', koreanWord: '해', chineseWord: '太阳' },
    { id: 68, categoryId: Category.StandaloneWords, englishWord: 'Crab', koreanWord: '게', chineseWord: '螃蟹' },
    { id: 69, categoryId: Category.StandaloneWords, englishWord: 'Wash face', koreanWord: '세수', chineseWord: '洗脸' },
    { id: 70, categoryId: Category.StandaloneWords, englishWord: 'Swing', koreanWord: '그네', chineseWord: '秋千' },
    { id: 71, categoryId: Category.StandaloneWords, englishWord: 'Camera', koreanWord: '카메라', chineseWord: '相机' },
    { id: 72, categoryId: Category.StandaloneWords, englishWord: 'Talk', koreanWord: '얘기', chineseWord: '说话' },
    { id: 73, categoryId: Category.StandaloneWords, englishWord: 'Pretty', koreanWord: '예쁘다', chineseWord: '漂亮' },
    { id: 74, categoryId: Category.StandaloneWords, englishWord: 'Calligraphy', koreanWord: '서예', chineseWord: '书法' },
    { id: 75, categoryId: Category.StandaloneWords, englishWord: 'Clock', koreanWord: '시계', chineseWord: '时钟' },
    { id: 76, categoryId: Category.StandaloneWords, englishWord: 'Snack', koreanWord: '과자', chineseWord: '零食' },
    { id: 77, categoryId: Category.StandaloneWords, englishWord: 'Dress shirt', koreanWord: '와이셔츠', chineseWord: '衬衫' },
    { id: 78, categoryId: Category.StandaloneWords, englishWord: 'Painter', koreanWord: '화가', chineseWord: '画家' },
    { id: 79, categoryId: Category.StandaloneWords, englishWord: 'Apple', koreanWord: '사과', chineseWord: '苹果' },
    { id: 80, categoryId: Category.StandaloneWords, englishWord: 'What', koreanWord: '뭐', chineseWord: '什么' },
    { id: 81, categoryId: Category.StandaloneWords, englishWord: 'Give', koreanWord: '줘요', chineseWord: '给' },
    { id: 82, categoryId: Category.StandaloneWords, englishWord: 'It\'s hot', koreanWord: '더워요', chineseWord: '热' },
    { id: 83, categoryId: Category.StandaloneWords, englishWord: 'It\'s cold', koreanWord: '추워요', chineseWord: '冷' },
    { id: 84, categoryId: Category.StandaloneWords, englishWord: 'Pig', koreanWord: '돼지', chineseWord: '猪' },
    { id: 85, categoryId: Category.StandaloneWords, englishWord: 'Why', koreanWord: '왜', chineseWord: '为什么' },
    { id: 86, categoryId: Category.StandaloneWords, englishWord: 'Waiter', koreanWord: '웨이터', chineseWord: '服务员' },
    { id: 87, categoryId: Category.StandaloneWords, englishWord: 'Sweater', koreanWord: '스웨터', chineseWord: '毛衣' },
    { id: 88, categoryId: Category.StandaloneWords, englishWord: 'Beef', koreanWord: '소고기', chineseWord: '牛肉' },
    { id: 89, categoryId: Category.StandaloneWords, englishWord: 'Memorize', koreanWord: '외우다', chineseWord: '记住' },
    { id: 90, categoryId: Category.StandaloneWords, englishWord: 'Company', koreanWord: '회사', chineseWord: '公司' },
    { id: 91, categoryId: Category.StandaloneWords, englishWord: 'Brains', koreanWord: '두뇌', chineseWord: '脑子' },
    { id: 92, categoryId: Category.StandaloneWords, englishWord: 'Ear', koreanWord: '귀', chineseWord: '耳朵' },
    { id: 93, categoryId: Category.StandaloneWords, englishWord: 'Rest', koreanWord: '쉬다', chineseWord: '休息' },
    { id: 94, categoryId: Category.StandaloneWords, englishWord: 'Rat', koreanWord: '쥐', chineseWord: '老鼠' },
    { id: 95, categoryId: Category.StandaloneWords, englishWord: 'Scissors', koreanWord: '가위', chineseWord: '剪刀' },
    { id: 96, categoryId: Category.StandaloneWords, englishWord: 'Doctor', koreanWord: '의사', chineseWord: '医生' },
    { id: 97, categoryId: Category.StandaloneWords, englishWord: 'Chair', koreanWord: '의자', chineseWord: '椅子' },
    { id: 98, categoryId: Category.StandaloneWords, englishWord: 'Meeting', koreanWord: '회의', chineseWord: '会议' },
    { id: 99, categoryId: Category.StandaloneWords, englishWord: 'Watermelon', koreanWord: '수박', chineseWord: '西瓜' },
    { id: 100, categoryId: Category.StandaloneWords, englishWord: 'Book', koreanWord: '책', chineseWord: '书' },
    { id: 101, categoryId: Category.StandaloneWords, englishWord: 'Money', koreanWord: '돈', chineseWord: '钱' },
    { id: 102, categoryId: Category.StandaloneWords, englishWord: 'Lemon', koreanWord: '레몬', chineseWord: '柠檬' },
    { id: 103, categoryId: Category.StandaloneWords, englishWord: 'Newspaper', koreanWord: '신문', chineseWord: '报纸' },
    { id: 104, categoryId: Category.StandaloneWords, englishWord: 'Umbrella', koreanWord: '우산', chineseWord: '雨伞' },
    { id: 105, categoryId: Category.StandaloneWords, englishWord: 'Soon', koreanWord: '곧', chineseWord: '很快' },
    { id: 106, categoryId: Category.StandaloneWords, englishWord: 'Strawberry', koreanWord: '딸기', chineseWord: '草莓' },
    { id: 107, categoryId: Category.StandaloneWords, englishWord: 'Water', koreanWord: '물', chineseWord: '水' },
    { id: 108, categoryId: Category.StandaloneWords, englishWord: 'Foot', koreanWord: '발', chineseWord: '脚' },
    { id: 109, categoryId: Category.StandaloneWords, englishWord: 'Pencil', koreanWord: '연필', chineseWord: '铅笔' },
    { id: 110, categoryId: Category.StandaloneWords, englishWord: 'Bear', koreanWord: '곰', chineseWord: '熊' },
    { id: 111, categoryId: Category.StandaloneWords, englishWord: 'Man', koreanWord: '남자', chineseWord: '男人' },
    { id: 112, categoryId: Category.StandaloneWords, englishWord: 'Mother (casual)', koreanWord: '엄마', chineseWord: '妈妈' },
    { id: 113, categoryId: Category.StandaloneWords, englishWord: 'Computer', koreanWord: '컴퓨터', chineseWord: '电脑' },
    { id: 114, categoryId: Category.StandaloneWords, englishWord: 'Cooked rice', koreanWord: '밥', chineseWord: '米饭' },
    { id: 115, categoryId: Category.StandaloneWords, englishWord: 'Mouth', koreanWord: '입', chineseWord: '嘴巴' },
    { id: 116, categoryId: Category.StandaloneWords, englishWord: 'Bag', koreanWord: '가방', chineseWord: '包' },
    { id: 117, categoryId: Category.StandaloneWords, englishWord: 'Ball', koreanWord: '공', chineseWord: '球' },
    { id: 118, categoryId: Category.StandaloneWords, englishWord: 'Refrigerator', koreanWord: '냉장고', chineseWord: '冰箱' },
    { id: 119, categoryId: Category.StandaloneWords, englishWord: 'Window', koreanWord: '창문', chineseWord: '窗户' },
    { id: 120, categoryId: Category.StandaloneWords, englishWord: 'Kitchen', koreanWord: '부엌', chineseWord: '厨房' },
    { id: 121, categoryId: Category.StandaloneWords, englishWord: 'Outside', koreanWord: '밖', chineseWord: '外面' },
    { id: 122, categoryId: Category.StandaloneWords, englishWord: 'Bottom', koreanWord: '밑', chineseWord: '底部' },
    { id: 123, categoryId: Category.StandaloneWords, englishWord: 'Comb', koreanWord: '빗', chineseWord: '梳子' },
    { id: 124, categoryId: Category.StandaloneWords, englishWord: 'Clothes', koreanWord: '옷', chineseWord: '衣服' },
    { id: 125, categoryId: Category.StandaloneWords, englishWord: 'Day', koreanWord: '낮', chineseWord: '白天' },
    { id: 126, categoryId: Category.StandaloneWords, englishWord: 'Flower', koreanWord: '꽃', chineseWord: '花' },
    { id: 127, categoryId: Category.StandaloneWords, englishWord: 'Light', koreanWord: '빛', chineseWord: '光' },
    { id: 128, categoryId: Category.StandaloneWords, englishWord: 'Knee', koreanWord: '무릎', chineseWord: '膝盖' },
    { id: 129, categoryId: Category.StandaloneWords, englishWord: 'Forest', koreanWord: '숲', chineseWord: '森林' },
    { id: 130, categoryId: Category.L1P1, englishWord: 'Name', koreanWord: '이름', chineseWord: '名字' },
    { id: 131, categoryId: Category.L1P1, englishWord: 'Job', koreanWord: '직업', chineseWord: '工作' },
    { id: 132, categoryId: Category.L1P1, englishWord: 'Nationality', koreanWord: '국적', chineseWord: '国籍' },
    { id: 133, categoryId: Category.L1P1, englishWord: 'Which', koreanWord: '어느', chineseWord: '哪个' },
    { id: 134, categoryId: Category.L1P1, englishWord: 'Country', koreanWord: '나라', chineseWord: '国家' },
    { id: 135, categoryId: Category.L1P1, englishWord: 'Person', koreanWord: '사람', chineseWord: '人' },
    { id: 136, categoryId: Category.L1P1, englishWord: 'Korea', koreanWord: '한국', chineseWord: '韩国' },
    { id: 137, categoryId: Category.L1P1, englishWord: 'Philippines', koreanWord: '필리핀', chineseWord: '菲律宾' },
    { id: 138, categoryId: Category.L1P1, englishWord: 'USA', koreanWord: '미국', chineseWord: '美国' },
    { id: 139, categoryId: Category.L1P1, englishWord: 'Egypt', koreanWord: '이집트', chineseWord: '埃及' },
    { id: 140, categoryId: Category.L1P1, englishWord: 'China', koreanWord: '중국', chineseWord: '中国' },
    { id: 141, categoryId: Category.L1P1, englishWord: 'Bangladesh', koreanWord: '방글라데시', chineseWord: '孟加拉国' },
    { id: 142, categoryId: Category.L1P1, englishWord: 'Teacher', koreanWord: '선생님', chineseWord: '老师' },
    { id: 143, categoryId: Category.L1P1, englishWord: 'Employee', koreanWord: '회사원', chineseWord: '职员' },
    { id: 144, categoryId: Category.L1P1, englishWord: 'English instructor', koreanWord: '영어강사', chineseWord: '英语教师' },
    { id: 145, categoryId: Category.L1P1, englishWord: 'Student', koreanWord: '학생', chineseWord: '学生' },
    { id: 146, categoryId: Category.L1P1, englishWord: 'Factory worker', koreanWord: '공장 직원', chineseWord: '工厂工人' },
    { id: 147, categoryId: Category.L1P1, englishWord: 'Salesman', koreanWord: '판매원', chineseWord: '销售员' },
    { id: 148, categoryId: Category.L1P1, englishWord: 'Housewife', koreanWord: '주부', chineseWord: '家庭主妇' },
    { id: 149, categoryId: Category.L1P1, englishWord: 'Elementary Student', koreanWord: '초등학생', chineseWord: '小学生' },
    { id: 150, categoryId: Category.L1P1, englishWord: 'New York', koreanWord: '뉴욕', chineseWord: '纽约' },
    { id: 151, categoryId: Category.L1P1, englishWord: 'English', koreanWord: '영어', chineseWord: '英语' },
    { id: 152, categoryId: Category.L1P1, englishWord: 'Korean', koreanWord: '한국어', chineseWord: '韩语' },
    { id: 153, categoryId: Category.L1P2, englishWord: 'Company', koreanWord: '회사', chineseWord: '公司' },
    { id: 154, categoryId: Category.L1P2, englishWord: 'Dormitory', koreanWord: '기숙사', chineseWord: '宿舍' },
    { id: 155, categoryId: Category.L1P2, englishWord: 'Desk', koreanWord: '책상', chineseWord: '书桌' },
    { id: 156, categoryId: Category.L1P2, englishWord: 'Chair', koreanWord: '의자', chineseWord: '椅子' },
    { id: 157, categoryId: Category.L1P2, englishWord: 'Bed', koreanWord: '침대', chineseWord: '床' },
    { id: 158, categoryId: Category.L1P2, englishWord: 'Computer', koreanWord: '컴퓨터', chineseWord: '电脑' },
    { id: 159, categoryId: Category.L1P2, englishWord: 'Mobile phone', koreanWord: '휴대 전화', chineseWord: '手机' },
    { id: 160, categoryId: Category.L1P2, englishWord: 'Clock', koreanWord: '시계', chineseWord: '时钟' },
    { id: 161, categoryId: Category.L1P2, englishWord: 'School', koreanWord: '학교', chineseWord: '学校' },
    { id: 162, categoryId: Category.L1P2, englishWord: 'Classroom', koreanWord: '교실', chineseWord: '教室' },
    { id: 163, categoryId: Category.L1P2, englishWord: 'Blackboard', koreanWord: '칠판', chineseWord: '黑板' },
    { id: 164, categoryId: Category.L1P2, englishWord: 'Map', koreanWord: '지도', chineseWord: '地图' },
    { id: 165, categoryId: Category.L1P2, englishWord: 'Book', koreanWord: '책', chineseWord: '书' },
    { id: 166, categoryId: Category.L1P2, englishWord: 'Pencil case', koreanWord: '필통', chineseWord: '铅笔盒' },
    { id: 167, categoryId: Category.L1P2, englishWord: 'Ballpoint pen', koreanWord: '볼펜', chineseWord: '圆珠笔' },
    { id: 168, categoryId: Category.L1P2, englishWord: 'Bathroom', koreanWord: '화장실', chineseWord: '洗手间' },
    { id: 169, categoryId: Category.L1P2, englishWord: 'Towel', koreanWord: '수건', chineseWord: '毛巾' },
    { id: 170, categoryId: Category.L1P2, englishWord: 'Mirror', koreanWord: '거울', chineseWord: '镜子' },
    { id: 171, categoryId: Category.L1P2, englishWord: 'Tissue', koreanWord: '휴지', chineseWord: '纸巾' },
    { id: 172, categoryId: Category.L1P2, englishWord: 'Living room', koreanWord: '거실', chineseWord: '客厅' },
    { id: 173, categoryId: Category.L1P2, englishWord: 'Air conditioner', koreanWord: '에어컨', chineseWord: '空调' },
    { id: 174, categoryId: Category.L1P2, englishWord: 'Sofa', koreanWord: '소파', chineseWord: '沙发' },
    { id: 175, categoryId: Category.L1P2, englishWord: 'Kitchen', koreanWord: '부엌', chineseWord: '厨房' },
    { id: 176, categoryId: Category.L1P2, englishWord: 'Dining table', koreanWord: '식탁', chineseWord: '餐桌' },
    { id: 177, categoryId: Category.L1P2, englishWord: 'Cup', koreanWord: '컵', chineseWord: '杯子' },
    { id: 178, categoryId: Category.L1P2, englishWord: 'Refrigerator', koreanWord: '냉장고', chineseWord: '冰箱' },
    { id: 179, categoryId: Category.L1P2, englishWord: 'But', koreanWord: '하지만', chineseWord: '但是' },
    { id: 180, categoryId: Category.L1P2, englishWord: 'Wardrobe', koreanWord: '옷장', chineseWord: '衣柜' },
    { id: 181, categoryId: Category.L1P2, englishWord: 'And', koreanWord: '그리고', chineseWord: '和' },
    { id: 182, categoryId: Category.L1P2, englishWord: 'There is', koreanWord: '있어요', chineseWord: '有' },
    { id: 183, categoryId: Category.L1P2, englishWord: 'There isn\'t any', koreanWord: '없어요', chineseWord: '没有' },
    { id: 184, categoryId: Category.L1P2, englishWord: 'Remote control', koreanWord: '리모콘', chineseWord: '遥控器' },
    { id: 185, categoryId: Category.L1P2, englishWord: 'Room', koreanWord: '방', chineseWord: '房间' },
    { id: 186, categoryId: Category.L1P2, englishWord: 'Which one', koreanWord: '뭐가', chineseWord: '哪个' },
    { id: 187, categoryId: Category.L1P2, englishWord: 'What is there', koreanWord: '뭐가 있어요', chineseWord: '有什么' },
    { id: 188, categoryId: Category.L1P2, englishWord: 'I don\'t have something', koreanWord: '뭐가 없어요', chineseWord: '没有什么' },
    { id: 189, categoryId: Category.L1P2, englishWord: 'Faucet', koreanWord: '수도꼭지', chineseWord: '水龙头' },
    { id: 190, categoryId: Category.L1P2, englishWord: 'Tile', koreanWord: '타일', chineseWord: '瓷砖' },
    { id: 191, categoryId: Category.L1P2, englishWord: 'However', koreanWord: '그런데', chineseWord: '不过' },
    { id: 192, categoryId: Category.L1P2, englishWord: '(in the)', koreanWord: '에', chineseWord: '在' },
    { id: 193, categoryId: Category.L1P1, englishWord: 'Nice to meet you', koreanWord: '만나서 반가워요', chineseWord: '很高兴认识你' },
    { id: 194, categoryId: Category.L1P3, englishWord: 'Cheap', koreanWord: '싸다', chineseWord: '便宜' },
    { id: 195, categoryId: Category.L1P3, englishWord: 'Expensive', koreanWord: '비싸다', chineseWord: '贵' },
    { id: 196, categoryId: Category.L1P3, englishWord: 'Many', koreanWord: '많다', chineseWord: '多' },
    { id: 197, categoryId: Category.L1P3, englishWord: 'Few', koreanWord: '적다', chineseWord: '少' },
    { id: 198, categoryId: Category.L1P3, englishWord: 'Big', koreanWord: '크다', chineseWord: '大' },
    { id: 199, categoryId: Category.L1P3, englishWord: 'Small', koreanWord: '작다', chineseWord: '小' },
    { id: 200, categoryId: Category.L1P3, englishWord: 'Delicious', koreanWord: '맛있다', chineseWord: '好吃' },
    { id: 201, categoryId: Category.L1P3, englishWord: 'Tasteless', koreanWord: '맛없다', chineseWord: '不好吃' },
    { id: 202, categoryId: Category.L1P3, englishWord: 'Difficult', koreanWord: '어렵다', chineseWord: '难' },
    { id: 203, categoryId: Category.L1P3, englishWord: 'Easy', koreanWord: '쉽다', chineseWord: '容易' },
    { id: 204, categoryId: Category.L1P3, englishWord: 'Cold', koreanWord: '춥다', chineseWord: '冷' },
    { id: 205, categoryId: Category.L1P3, englishWord: 'Hot', koreanWord: '덥다', chineseWord: '热' },
    { id: 206, categoryId: Category.L1P3, englishWord: 'Interesting', koreanWord: '재미있다', chineseWord: '有趣' },
    { id: 207, categoryId: Category.L1P3, englishWord: 'Boring', koreanWord: '재미없다', chineseWord: '无聊' },
    { id: 208, categoryId: Category.L1P3, englishWord: 'Good', koreanWord: '좋다', chineseWord: '好' },
    { id: 209, categoryId: Category.L1P3, englishWord: 'Bad', koreanWord: '나쁘다', chineseWord: '坏' },
    { id: 210, categoryId: Category.L1P3, englishWord: 'Pretty', koreanWord: '예쁘다', chineseWord: '漂亮' },
    { id: 211, categoryId: Category.L1P3, englishWord: 'Busy', koreanWord: '바쁘다', chineseWord: '忙' },
    { id: 212, categoryId: Category.L1P3, englishWord: 'Sick', koreanWord: '아프다', chineseWord: '病' },
    { id: 213, categoryId: Category.L1P3, englishWord: 'Hungry', koreanWord: '배가 고프다', chineseWord: '饿' },
    { id: 214, categoryId: Category.L1P3, englishWord: 'Cook hometown food', koreanWord: '고향 음식을 요리하다', chineseWord: '做家乡菜' },
    { id: 215, categoryId: Category.L1P3, englishWord: 'Read a book', koreanWord: '책을 읽다', chineseWord: '读书' },
    { id: 216, categoryId: Category.L1P3, englishWord: 'Study Korean', koreanWord: '한국어를 공부하다', chineseWord: '学习韩语' },
    { id: 217, categoryId: Category.L1P3, englishWord: 'Watch TV', koreanWord: '텔레비전을 보다', chineseWord: '看电视' },
    { id: 218, categoryId: Category.L1P3, englishWord: 'Drink coffee', koreanWord: '커피를 마시다', chineseWord: '喝咖啡' },
    { id: 219, categoryId: Category.L1P3, englishWord: 'Clean the room', koreanWord: '방을 청소하다', chineseWord: '打扫房间' },
    { id: 220, categoryId: Category.L1P3, englishWord: 'Eat bread', koreanWord: '빵을 먹다', chineseWord: '吃面包' },
    { id: 221, categoryId: Category.L1P3, englishWord: 'Meet a friend', koreanWord: '친구를 만나다', chineseWord: '见朋友' },
    { id: 222, categoryId: Category.L1P3, englishWord: 'Buy clothes', koreanWord: '옷을 사다', chineseWord: '买衣服' },
    { id: 223, categoryId: Category.L1P3, englishWord: 'Work', koreanWord: '일하다', chineseWord: '工作' },
    { id: 224, categoryId: Category.L1P3, englishWord: 'Sleep', koreanWord: '자다', chineseWord: '睡觉' },
    { id: 225, categoryId: Category.L1P3, englishWord: 'Exercise', koreanWord: '운동하다', chineseWord: '运动' },
    { id: 226, categoryId: Category.L1P3, englishWord: 'Students', koreanWord: '학생들', chineseWord: '学生们' },
    { id: 227, categoryId: Category.L1P3, englishWord: 'YouTube', koreanWord: '유튜브', chineseWord: 'YouTube' },
    { id: 228, categoryId: Category.L1P3, englishWord: 'Hard hat', koreanWord: '안전모', chineseWord: '安全帽' },
    { id: 229, categoryId: Category.L1P3, englishWord: 'Tray', koreanWord: '쟁반', chineseWord: '托盘' },
    { id: 230, categoryId: Category.L1P3, englishWord: 'Food', koreanWord: '음식', chineseWord: '食物' },
    { id: 231, categoryId: Category.L1P3, englishWord: 'Weather', koreanWord: '날씨', chineseWord: '天气' },
    { id: 232, categoryId: Category.L1P4, englishWord: 'School', koreanWord: '학교', chineseWord: '学校' },
    { id: 233, categoryId: Category.L1P4, englishWord: 'Convenience store', koreanWord: '편의점', chineseWord: '便利店' },
    { id: 234, categoryId: Category.L1P4, englishWord: 'Company', koreanWord: '회사', chineseWord: '公司' },
    { id: 235, categoryId: Category.L1P4, englishWord: 'Bank', koreanWord: '은행', chineseWord: '银行' },
    { id: 236, categoryId: Category.L1P4, englishWord: 'House', koreanWord: '집', chineseWord: '房子' },
    { id: 237, categoryId: Category.L1P4, englishWord: 'Restaurant', koreanWord: '식당', chineseWord: '餐厅' },
    { id: 238, categoryId: Category.L1P4, englishWord: 'Cafe', koreanWord: '카페', chineseWord: '咖啡馆' },
    { id: 239, categoryId: Category.L1P4, englishWord: 'Hospital', koreanWord: '병원', chineseWord: '医院' },
    { id: 240, categoryId: Category.L1P4, englishWord: 'Pharmacy', koreanWord: '약국', chineseWord: '药店' },
    { id: 241, categoryId: Category.L1P4, englishWord: 'Market', koreanWord: '시장', chineseWord: '市场' },
    { id: 242, categoryId: Category.L1P4, englishWord: 'Mart', koreanWord: '마트', chineseWord: '超市' },
    { id: 243, categoryId: Category.L1P4, englishWord: 'Movie theater', koreanWord: '영화관', chineseWord: '电影院' },
    { id: 244, categoryId: Category.L1P4, englishWord: 'Theater', koreanWord: '극장', chineseWord: '剧院' },
    { id: 245, categoryId: Category.L1P4, englishWord: 'Department store', koreanWord: '백화점', chineseWord: '百货商店' },
    { id: 246, categoryId: Category.L1P4, englishWord: 'Korean sauna', koreanWord: '찜질방', chineseWord: '韩国桑拿' },
    { id: 247, categoryId: Category.L1P4, englishWord: 'Gym', koreanWord: '헬스장', chineseWord: '健身房' },
    { id: 248, categoryId: Category.L1P4, englishWord: 'Karaoke room', koreanWord: '노래방', chineseWord: '卡拉OK房' },
    { id: 249, categoryId: Category.L1P4, englishWord: 'PC room', koreanWord: '피시방(PC방)', chineseWord: '网吧' },
    { id: 250, categoryId: Category.L1P4, englishWord: 'Beauty salon', koreanWord: '미용실', chineseWord: '美容院' },
    { id: 251, categoryId: Category.L1P4, englishWord: 'Laundromat', koreanWord: '빨래방', chineseWord: '自助洗衣店' },
    { id: 252, categoryId: Category.L1P4, englishWord: 'Post office', koreanWord: '우체국', chineseWord: '邮局' },
    { id: 253, categoryId: Category.L1P4, englishWord: 'Bookstore', koreanWord: '서점', chineseWord: '书店' },
    { id: 254, categoryId: Category.L1P4, englishWord: 'Company cafeteria', koreanWord: '회사 식당', chineseWord: '公司食堂' },
    { id: 255, categoryId: Category.L1P4, englishWord: 'Staff cafeteria', koreanWord: '직원 식당', chineseWord: '职工食堂' },
    { id: 256, categoryId: Category.L1P4, englishWord: 'Nearby', koreanWord: '근처', chineseWord: '附近' },
    { id: 257, categoryId: Category.L1P4, englishWord: 'Outside', koreanWord: '밖', chineseWord: '外面' },
    { id: 258, categoryId: Category.L1P4, englishWord: 'Park', koreanWord: '공원', chineseWord: '公园' },
    { id: 259, categoryId: Category.L1P4, englishWord: 'Very', koreanWord: '아주', chineseWord: '非常' },
    { id: 260, categoryId: Category.L1P4, englishWord: 'Husband', koreanWord: '남편', chineseWord: '丈夫' },
    { id: 261, categoryId: Category.L1P4, englishWord: 'Guitar', koreanWord: '기타', chineseWord: '吉他' },
    { id: 262, categoryId: Category.L1P4, englishWord: 'Weekend', koreanWord: '주말', chineseWord: '周末' },
    { id: 263, categoryId: Category.L1P4, englishWord: 'Culture center', koreanWord: '문화 센터', chineseWord: '文化中心' },
    { id: 264, categoryId: Category.L1P4, englishWord: 'To learn', koreanWord: '배우다', chineseWord: '学习' },
    { id: 265, categoryId: Category.L1P5, englishWord: 'What month', koreanWord: '몇 월', chineseWord: '几月' },
    { id: 266, categoryId: Category.L1P5, englishWord: 'What day', koreanWord: '며칠', chineseWord: '几号' },
    { id: 267, categoryId: Category.L1P5, englishWord: 'Zero', koreanWord: '영/공', chineseWord: '零' },
    { id: 268, categoryId: Category.L1P5, englishWord: 'One', koreanWord: '일', chineseWord: '一' },
    { id: 269, categoryId: Category.L1P5, englishWord: 'Two', koreanWord: '이', chineseWord: '二' },
    { id: 270, categoryId: Category.L1P5, englishWord: 'Three', koreanWord: '삼', chineseWord: '三' },
    { id: 271, categoryId: Category.L1P5, englishWord: 'Four', koreanWord: '사', chineseWord: '四' },
    { id: 272, categoryId: Category.L1P5, englishWord: 'Five', koreanWord: '오', chineseWord: '五' },
    { id: 273, categoryId: Category.L1P5, englishWord: 'Six', koreanWord: '육', chineseWord: '六' },
    { id: 274, categoryId: Category.L1P5, englishWord: 'Seven', koreanWord: '칠', chineseWord: '七' },
    { id: 275, categoryId: Category.L1P5, englishWord: 'Eight', koreanWord: '팔', chineseWord: '八' },
    { id: 276, categoryId: Category.L1P5, englishWord: 'Nine', koreanWord: '구', chineseWord: '九' },
    { id: 277, categoryId: Category.L1P5, englishWord: 'Ten', koreanWord: '십', chineseWord: '十' },
    { id: 278, categoryId: Category.L1P5, englishWord: 'Twenty', koreanWord: '이십', chineseWord: '二十' },
    { id: 279, categoryId: Category.L1P5, englishWord: 'Thirty', koreanWord: '삼십', chineseWord: '三十' },
    { id: 280, categoryId: Category.L1P5, englishWord: 'Today', koreanWord: '오늘', chineseWord: '今天' },
    { id: 281, categoryId: Category.L1P5, englishWord: 'Tomorrow', koreanWord: '내일', chineseWord: '明天' },
    { id: 282, categoryId: Category.L1P5, englishWord: 'Yesterday', koreanWord: '어제', chineseWord: '昨天' },
    { id: 283, categoryId: Category.L1P5, englishWord: 'Last week', koreanWord: '지난주', chineseWord: '上周' },
    { id: 284, categoryId: Category.L1P5, englishWord: 'This week', koreanWord: '이번 주', chineseWord: '这周' },
    { id: 285, categoryId: Category.L1P5, englishWord: 'Next week', koreanWord: '다음 주', chineseWord: '下周' },
    { id: 286, categoryId: Category.L1P5, englishWord: 'Day of the week', koreanWord: '요일', chineseWord: '星期' },
    { id: 287, categoryId: Category.L1P5, englishWord: 'Monday', koreanWord: '월요일', chineseWord: '星期一' },
    { id: 288, categoryId: Category.L1P5, englishWord: 'Tuesday', koreanWord: '화요일', chineseWord: '星期二' },
    { id: 289, categoryId: Category.L1P5, englishWord: 'Wednesday', koreanWord: '수요일', chineseWord: '星期三' },
    { id: 290, categoryId: Category.L1P5, englishWord: 'Thursday', koreanWord: '목요일', chineseWord: '星期四' },
    { id: 291, categoryId: Category.L1P5, englishWord: 'Friday', koreanWord: '금요일', chineseWord: '星期五' },
    { id: 292, categoryId: Category.L1P5, englishWord: 'Saturday', koreanWord: '토요일', chineseWord: '星期六' },
    { id: 293, categoryId: Category.L1P5, englishWord: 'Sunday', koreanWord: '일요일', chineseWord: '星期天' },
    { id: 294, categoryId: Category.L1P5, englishWord: 'Doctor', koreanWord: '의사', chineseWord: '医生' },
    { id: 295, categoryId: Category.L1P5, englishWord: 'Building', koreanWord: '빌딩', chineseWord: '大楼' },
    { id: 296, categoryId: Category.L1P5, englishWord: '3rd floor, 17th room', koreanWord: '(3)층 (17)호', chineseWord: '三楼17号' },
    { id: 297, categoryId: Category.L1P5, englishWord: 'Business card', koreanWord: '명함', chineseWord: '名片' },
    { id: 298, categoryId: Category.L1P6, englishWord: 'Zero', koreanWord: '영/공', chineseWord: '零' },
    { id: 299, categoryId: Category.L1P6, englishWord: 'One', koreanWord: '하나', chineseWord: '一' },
    { id: 300, categoryId: Category.L1P6, englishWord: 'Two', koreanWord: '둘', chineseWord: '二' },
    { id: 301, categoryId: Category.L1P6, englishWord: 'Three', koreanWord: '셋', chineseWord: '三' },
    { id: 302, categoryId: Category.L1P6, englishWord: 'Four', koreanWord: '넷', chineseWord: '四' },
    { id: 303, categoryId: Category.L1P6, englishWord: 'Five', koreanWord: '다섯', chineseWord: '五' },
    { id: 304, categoryId: Category.L1P6, englishWord: 'Six', koreanWord: '여섯', chineseWord: '六' },
    { id: 305, categoryId: Category.L1P6, englishWord: 'Seven', koreanWord: '일곱', chineseWord: '七' },
    { id: 306, categoryId: Category.L1P6, englishWord: 'Eight', koreanWord: '여덟', chineseWord: '八' },
    { id: 307, categoryId: Category.L1P6, englishWord: 'Nine', koreanWord: '아홉', chineseWord: '九' },
    { id: 308, categoryId: Category.L1P6, englishWord: 'Ten', koreanWord: '열', chineseWord: '十' },
    { id: 309, categoryId: Category.L1P6, englishWord: 'Eleven', koreanWord: '열하나', chineseWord: '十一' },
    { id: 310, categoryId: Category.L1P6, englishWord: 'Twelve', koreanWord: '열둘', chineseWord: '十二' },
    { id: 311, categoryId: Category.L1P6, englishWord: 'Twenty', koreanWord: '스물', chineseWord: '二十' },
    { id: 312, categoryId: Category.L1P6, englishWord: 'Thirty', koreanWord: '서른', chineseWord: '三十' },
    { id: 313, categoryId: Category.L1P6, englishWord: 'Forty', koreanWord: '마흔', chineseWord: '四十' },
    { id: 314, categoryId: Category.L1P6, englishWord: 'Fifty', koreanWord: '쉰', chineseWord: '五十' },
    { id: 315, categoryId: Category.L1P6, englishWord: 'Sixty', koreanWord: '예순', chineseWord: '六十' },
    { id: 316, categoryId: Category.L1P6, englishWord: 'Seventy', koreanWord: '일흔', chineseWord: '七十' },
    { id: 317, categoryId: Category.L1P6, englishWord: 'Eighty', koreanWord: '여든', chineseWord: '八十' },
    { id: 318, categoryId: Category.L1P6, englishWord: 'Ninety', koreanWord: '아흔', chineseWord: '九十' },
    { id: 319, categoryId: Category.L1P6, englishWord: 'Hour', koreanWord: '시', chineseWord: '小时' },
    { id: 320, categoryId: Category.L1P6, englishWord: 'Minute', koreanWord: '분', chineseWord: '分钟' },
    { id: 321, categoryId: Category.L1P6, englishWord: 'Half', koreanWord: '반', chineseWord: '半' },
    { id: 322, categoryId: Category.L1P6, englishWord: 'To get up', koreanWord: '일어나다', chineseWord: '起床' },
    { id: 323, categoryId: Category.L1P6, englishWord: 'To wash one\'s face', koreanWord: '세수하다', chineseWord: '洗脸' },
    { id: 324, categoryId: Category.L1P6, englishWord: 'To put on clothes', koreanWord: '옷을 입다', chineseWord: '穿衣服' },
    { id: 325, categoryId: Category.L1P6, englishWord: 'Morning', koreanWord: '아침', chineseWord: '早晨' },
    { id: 326, categoryId: Category.L1P6, englishWord: 'Daytime', koreanWord: '낮', chineseWord: '白天' },
    { id: 327, categoryId: Category.L1P6, englishWord: 'Evening', koreanWord: '저녁', chineseWord: '晚上' },
    { id: 328, categoryId: Category.L1P6, englishWord: 'Night', koreanWord: '밤', chineseWord: '夜晚' },
    { id: 329, categoryId: Category.L1P6, englishWord: 'Dawn', koreanWord: '새벽', chineseWord: '黎明' },
    { id: 330, categoryId: Category.L1P6, englishWord: 'To meet a friend', koreanWord: '친구를 만나다', chineseWord: '见朋友' },
    { id: 331, categoryId: Category.L1P6, englishWord: 'To learn Korean', koreanWord: '한국어를 배우다', chineseWord: '学习韩语' },
    { id: 332, categoryId: Category.L1P6, englishWord: 'To go to work', koreanWord: '출근하다', chineseWord: '上班' },
    { id: 333, categoryId: Category.L1P6, englishWord: 'To work', koreanWord: '일하다', chineseWord: '工作' },
    { id: 334, categoryId: Category.L1P6, englishWord: 'To leave work', koreanWord: '퇴근하다', chineseWord: '下班' },
    { id: 335, categoryId: Category.L1P6, englishWord: 'Tennis', koreanWord: '테니스', chineseWord: '网球' },
    { id: 336, categoryId: Category.L1P7, englishWord: 'Snack bar', koreanWord: '분식집', chineseWord: '小吃店' },
    { id: 337, categoryId: Category.L1P7, englishWord: 'Kimbap', koreanWord: '김밥', chineseWord: '紫菜包饭' },
    { id: 338, categoryId: Category.L1P7, englishWord: 'Tteokbokki', koreanWord: '떡볶이', chineseWord: '辣炒年糕' },
    { id: 339, categoryId: Category.L1P7, englishWord: 'Sundae (Korean blood sausage)', koreanWord: '순대', chineseWord: '韩国血肠' },
    { id: 340, categoryId: Category.L1P7, englishWord: 'Ramen', koreanWord: '라면', chineseWord: '拉面' },
    { id: 341, categoryId: Category.L1P7, englishWord: 'Korean restaurant', koreanWord: '한식집', chineseWord: '韩餐馆' },
    { id: 342, categoryId: Category.L1P7, englishWord: 'Samgyetang (chicken soup with ginseng)', koreanWord: '삼계탕', chineseWord: '参鸡汤' },
    { id: 343, categoryId: Category.L1P7, englishWord: 'Bulgogi (marinated beef)', koreanWord: '불고기', chineseWord: '烤肉' },
    { id: 344, categoryId: Category.L1P7, englishWord: 'Samgyeopsal (pork belly)', koreanWord: '삼겹살', chineseWord: '五花肉' },
    { id: 345, categoryId: Category.L1P7, englishWord: 'Kimchi stew', koreanWord: '김치찌개', chineseWord: '泡菜汤' },
    { id: 346, categoryId: Category.L1P7, englishWord: 'Bibimbap (mixed rice with vegetables)', koreanWord: '비빔밥', chineseWord: '石锅拌饭' },
    { id: 347, categoryId: Category.L1P7, englishWord: 'Doenjang stew (soybean paste stew)', koreanWord: '된장찌개', chineseWord: '大酱汤' },
    { id: 348, categoryId: Category.L1P7, englishWord: 'Japanese restaurant', koreanWord: '일식집', chineseWord: '日餐馆' },
    { id: 349, categoryId: Category.L1P7, englishWord: 'Sashimi', koreanWord: '생선회', chineseWord: '生鱼片' },
    { id: 350, categoryId: Category.L1P7, englishWord: 'Sushi', koreanWord: '초밥', chineseWord: '寿司' },
    { id: 351, categoryId: Category.L1P7, englishWord: 'Udon', koreanWord: '우동', chineseWord: '乌冬面' },
    { id: 352, categoryId: Category.L1P7, englishWord: 'Tonkatsu (pork cutlet)', koreanWord: '돈가스', chineseWord: '炸猪排' },
    { id: 353, categoryId: Category.L1P7, englishWord: 'Chinese restaurant', koreanWord: '중국집', chineseWord: '中餐馆' },
    { id: 354, categoryId: Category.L1P7, englishWord: 'Jajangmyeon (black bean noodles)', koreanWord: '짜장면', chineseWord: '炸酱面' },
    { id: 355, categoryId: Category.L1P7, englishWord: 'Jjamppong (spicy seafood noodle soup)', koreanWord: '짬뽕', chineseWord: '辣海鲜面' },
    { id: 356, categoryId: Category.L1P7, englishWord: 'Dumplings', koreanWord: '만두', chineseWord: '饺子' },
    { id: 357, categoryId: Category.L1P7, englishWord: 'Sweet and sour pork', koreanWord: '탕수육', chineseWord: '糖醋肉' },
    { id: 358, categoryId: Category.L1P7, englishWord: 'Italian restaurant', koreanWord: '이탈리아 식당', chineseWord: '意大利餐馆' },
    { id: 359, categoryId: Category.L1P7, englishWord: 'Pizza', koreanWord: '피자', chineseWord: '披萨' },
    { id: 360, categoryId: Category.L1P7, englishWord: 'Hamburger', koreanWord: '햄버거', chineseWord: '汉堡' },
    { id: 361, categoryId: Category.L1P7, englishWord: 'Spaghetti', koreanWord: '스파게티', chineseWord: '意大利面' },
    { id: 362, categoryId: Category.L1P7, englishWord: 'Salad', koreanWord: '샐러드', chineseWord: '沙拉' },
    { id: 363, categoryId: Category.L1P7, englishWord: 'To wait', koreanWord: '기다리다', chineseWord: '等待' },
    { id: 364, categoryId: Category.L1P7, englishWord: 'Side dishes', koreanWord: '반찬', chineseWord: '小菜' },
    { id: 365, categoryId: Category.L1P7, englishWord: 'Spoon', koreanWord: '숟가락', chineseWord: '勺子' },
    { id: 366, categoryId: Category.L1P7, englishWord: 'Chopsticks', koreanWord: '젓가락', chineseWord: '筷子' },
    { id: 367, categoryId: Category.L1P7, englishWord: 'Bowl', koreanWord: '그릇', chineseWord: '碗' },
    { id: 368, categoryId: Category.L1P7, englishWord: 'To order', koreanWord: '주문하다', chineseWord: '点餐' },
    { id: 369, categoryId: Category.L1P7, englishWord: 'Menu', koreanWord: '메뉴', chineseWord: '菜单' },
    { id: 370, categoryId: Category.L1P7, englishWord: 'Write your name', koreanWord: '이름을 쓰세요', chineseWord: '请写名字' },
    { id: 371, categoryId: Category.L1P7, englishWord: 'Please give me more side dishes', koreanWord: '반찬 좀 더 주세요', chineseWord: '请再给我一些小菜' },
    { id: 372, categoryId: Category.L1P7, englishWord: 'Please give me three servings of bulgogi', koreanWord: '불고기 3인분 주세요', chineseWord: '请给我三份烤肉' },
    { id: 373, categoryId: Category.L1P7, englishWord: 'Please give me some water', koreanWord: '물 좀 주세요', chineseWord: '请给我一些水' },
    { id: 374, categoryId: Category.L1P8, englishWord: 'Large', koreanWord: '대', chineseWord: '大' },
    { id: 375, categoryId: Category.L1P8, englishWord: 'Cup', koreanWord: '잔', chineseWord: '杯子' },
    { id: 376, categoryId: Category.L1P8, englishWord: 'Sheet', koreanWord: '장', chineseWord: '张' },
    { id: 377, categoryId: Category.L1P8, englishWord: 'Book', koreanWord: '권', chineseWord: '本' },
    { id: 378, categoryId: Category.L1P8, englishWord: 'Animal', koreanWord: '마리', chineseWord: '只' },
    { id: 379, categoryId: Category.L1P8, englishWord: 'Person', koreanWord: '명', chineseWord: '名' },
    { id: 380, categoryId: Category.L1P8, englishWord: 'Piece', koreanWord: '개', chineseWord: '个' },
    { id: 381, categoryId: Category.L1P8, englishWord: 'Slice, piece', koreanWord: '조각', chineseWord: '片' },
    { id: 382, categoryId: Category.L1P8, englishWord: 'Bottle', koreanWord: '병', chineseWord: '瓶' },
    { id: 383, categoryId: Category.L1P8, englishWord: 'Water', koreanWord: '물', chineseWord: '水' },
    { id: 384, categoryId: Category.L1P8, englishWord: 'Coffee', koreanWord: '커피', chineseWord: '咖啡' },
    { id: 385, categoryId: Category.L1P8, englishWord: 'Puppy', koreanWord: '강아지', chineseWord: '小狗' },
    { id: 386, categoryId: Category.L1P8, englishWord: 'Magazine', koreanWord: '잡지', chineseWord: '杂志' },
    { id: 387, categoryId: Category.L1P8, englishWord: 'Photo', koreanWord: '사진', chineseWord: '照片' },
    { id: 388, categoryId: Category.L1P8, englishWord: 'Laptop', koreanWord: '노트북', chineseWord: '笔记本电脑' },
    { id: 389, categoryId: Category.L1P8, englishWord: 'Green tea', koreanWord: '녹차', chineseWord: '绿茶' },
    { id: 390, categoryId: Category.L1P8, englishWord: 'Vegetable', koreanWord: '채소', chineseWord: '蔬菜' },
    { id: 391, categoryId: Category.L1P8, englishWord: 'Vacuum cleaner', koreanWord: '청소기', chineseWord: '吸尘器' },
    { id: 392, categoryId: Category.L1P8, englishWord: 'Fast', koreanWord: '빠르다', chineseWord: '快' },
    { id: 393, categoryId: Category.L1P8, englishWord: 'Envelope, bag', koreanWord: '봉투', chineseWord: '信封' },
    { id: 394, categoryId: Category.L1P8, englishWord: 'Chicken', koreanWord: '닭', chineseWord: '鸡' },
    { id: 395, categoryId: Category.L1P8, englishWord: 'Chicken meat', koreanWord: '닭고기', chineseWord: '鸡肉' },
    { id: 396, categoryId: Category.L1P8, englishWord: 'Egg', koreanWord: '계란', chineseWord: '鸡蛋' },
    { id: 397, categoryId: Category.L1P8, englishWord: 'Discount', koreanWord: '할인', chineseWord: '折扣' },
    { id: 398, categoryId: Category.L1P8, englishWord: 'Product', koreanWord: '상품', chineseWord: '产品' },
    { id: 399, categoryId: Category.L1P9, englishWord: 'To rest at home', koreanWord: '집에서 쉬다', chineseWord: '在家休息' },
    { id: 400, categoryId: Category.L1P9, englishWord: 'To clean', koreanWord: '청소를 하다', chineseWord: '打扫' },
    { id: 401, categoryId: Category.L1P9, englishWord: 'To do the laundry', koreanWord: '빨래를 하다', chineseWord: '洗衣服' },
    { id: 402, categoryId: Category.L1P9, englishWord: 'To play soccer', koreanWord: '축구를 하다', chineseWord: '踢足球' },
    { id: 403, categoryId: Category.L1P9, englishWord: 'To go to the mountain', koreanWord: '산에 가다', chineseWord: '去爬山' },
    { id: 404, categoryId: Category.L1P9, englishWord: 'To take a walk', koreanWord: '산책하다', chineseWord: '散步' },
    { id: 405, categoryId: Category.L1P9, englishWord: 'To meet a friend', koreanWord: '친구를 만나다', chineseWord: '见朋友' },
    { id: 406, categoryId: Category.L1P9, englishWord: 'To do part-time work', koreanWord: '아르바이트를 하다', chineseWord: '做兼职' },
    { id: 407, categoryId: Category.L1P9, englishWord: 'To learn Korean', koreanWord: '한국어를 배우다', chineseWord: '学韩语' },
    { id: 408, categoryId: Category.L1P9, englishWord: 'Park', koreanWord: '공원', chineseWord: '公园' },
    { id: 409, categoryId: Category.L1P9, englishWord: 'To ride a bicycle', koreanWord: '자전거를 타다', chineseWord: '骑自行车' },
    { id: 410, categoryId: Category.L1P9, englishWord: 'To play ball', koreanWord: '공놀이를 하다', chineseWord: '玩球' },
    { id: 411, categoryId: Category.L1P9, englishWord: 'Market', koreanWord: '시장', chineseWord: '市场' },
    { id: 412, categoryId: Category.L1P9, englishWord: 'To buy fruit', koreanWord: '과일을 사다', chineseWord: '买水果' },
    { id: 413, categoryId: Category.L1P9, englishWord: 'To buy shoes', koreanWord: '신발을 사다', chineseWord: '买鞋' },
    { id: 414, categoryId: Category.L1P9, englishWord: 'Department store', koreanWord: '백화점', chineseWord: '百货商店' },
    { id: 415, categoryId: Category.L1P9, englishWord: 'To shop', koreanWord: '쇼핑하다', chineseWord: '购物' },
    { id: 416, categoryId: Category.L1P9, englishWord: 'To eat dinner', koreanWord: '저녁을 먹다', chineseWord: '吃晚饭' },
    { id: 417, categoryId: Category.L1P9, englishWord: 'Cafe', koreanWord: '카페', chineseWord: '咖啡馆' },
    { id: 418, categoryId: Category.L1P9, englishWord: 'To talk', koreanWord: '이야기를 하다', chineseWord: '聊天' },
    { id: 419, categoryId: Category.L1P9, englishWord: 'To drink tea', koreanWord: '차를 마시다', chineseWord: '喝茶' },
    { id: 420, categoryId: Category.L1P9, englishWord: 'Home', koreanWord: '집', chineseWord: '家' },
    { id: 421, categoryId: Category.L1P9, englishWord: 'To have a meal', koreanWord: '식사를 하다', chineseWord: '吃饭' },
    { id: 422, categoryId: Category.L1P9, englishWord: 'To watch television', koreanWord: '텔레비전을 보다', chineseWord: '看电视' },
    { id: 423, categoryId: Category.L1P9, englishWord: 'Company', koreanWord: '회사', chineseWord: '公司' },
    { id: 424, categoryId: Category.L1P9, englishWord: 'To work', koreanWord: '일하다', chineseWord: '工作' },
    { id: 425, categoryId: Category.L1P9, englishWord: 'To answer the phone', koreanWord: '전화를 받다', chineseWord: '接电话' },
    { id: 426, categoryId: Category.L1P9, englishWord: 'Jeonju', koreanWord: '전주', chineseWord: '全州' },
    { id: 427, categoryId: Category.L1P9, englishWord: 'Hanok village', koreanWord: '한옥 마을', chineseWord: '韩屋村' },
    { id: 428, categoryId: Category.L1P9, englishWord: 'To wear hanbok', koreanWord: '한복을 입다', chineseWord: '穿韩服' },
    { id: 429, categoryId: Category.L1P9, englishWord: 'To walk', koreanWord: '걷다', chineseWord: '走路' },
    { id: 430, categoryId: Category.L1P9, englishWord: 'Bridge', koreanWord: '다리', chineseWord: '桥' },
    { id: 431, categoryId: Category.L1P9, englishWord: 'But', koreanWord: '그렇지만', chineseWord: '但是' },
    { id: 432, categoryId: Category.L1P9, englishWord: 'To be joyful', koreanWord: '즐겁다', chineseWord: '开心' },
    { id: 433, categoryId: Category.L1P10, englishWord: 'Grandmother', koreanWord: '할머니', chineseWord: '奶奶' },
    { id: 434, categoryId: Category.L1P10, englishWord: 'Grandfather', koreanWord: '할아버지', chineseWord: '爷爷' },
    { id: 435, categoryId: Category.L1P10, englishWord: 'Maternal grandmother', koreanWord: '외할머니', chineseWord: '外婆' },
    { id: 436, categoryId: Category.L1P10, englishWord: 'Maternal grandfather', koreanWord: '외할아버지', chineseWord: '外公' },
    { id: 437, categoryId: Category.L1P10, englishWord: 'Mother (mom)', koreanWord: '어머니(엄마)', chineseWord: '母亲（妈妈）' },
    { id: 438, categoryId: Category.L1P10, englishWord: 'Father (dad)', koreanWord: '아버지(아빠)', chineseWord: '父亲（爸爸）' },
    { id: 439, categoryId: Category.L1P10, englishWord: 'Older sister (for females)', koreanWord: '언니', chineseWord: '姐姐（女用）' },
    { id: 440, categoryId: Category.L1P10, englishWord: 'Older brother (for females)', koreanWord: '오빠', chineseWord: '哥哥（女用）' },
    { id: 441, categoryId: Category.L1P10, englishWord: 'I', koreanWord: '나', chineseWord: '我' },
    { id: 442, categoryId: Category.L1P10, englishWord: 'Younger sister', koreanWord: '여동생', chineseWord: '妹妹' },
    { id: 443, categoryId: Category.L1P10, englishWord: 'Younger brother', koreanWord: '남동생', chineseWord: '弟弟' },
    { id: 444, categoryId: Category.L1P10, englishWord: 'Older sister (for males)', koreanWord: '누나', chineseWord: '姐姐（男用）' },
    { id: 445, categoryId: Category.L1P10, englishWord: 'Older brother (for males)', koreanWord: '형', chineseWord: '哥哥（男用）' },
    { id: 446, categoryId: Category.L1P10, englishWord: 'Honorific language', koreanWord: '높임말', chineseWord: '敬语' },
    { id: 447, categoryId: Category.L1P10, englishWord: 'Surname', koreanWord: '성함', chineseWord: '姓氏' },
    { id: 448, categoryId: Category.L1P10, englishWord: 'Age', koreanWord: '연세', chineseWord: '年龄' },
    { id: 449, categoryId: Category.L1P10, englishWord: 'Birthday', koreanWord: '생신', chineseWord: '生日' },
    { id: 450, categoryId: Category.L1P10, englishWord: 'Person (honorific)', koreanWord: '분', chineseWord: '位（敬语）' },
    { id: 451, categoryId: Category.L1P10, englishWord: 'To be (honorific)', koreanWord: '계시다', chineseWord: '在（敬语）' },
    { id: 452, categoryId: Category.L1P10, englishWord: 'To eat (honorific)', koreanWord: '드시다/잡수시다', chineseWord: '吃（敬语）' },
    { id: 453, categoryId: Category.L1P10, englishWord: 'To drink (honorific)', koreanWord: '주무시다', chineseWord: '喝（敬语）' },
    { id: 454, categoryId: Category.L1P10, englishWord: 'To return (honorific)', koreanWord: '돌아가시다', chineseWord: '回去（敬语）' },
    { id: 455, categoryId: Category.L1P10, englishWord: 'To speak (honorific)', koreanWord: '말씀하시다', chineseWord: '说话（敬语）' },
    { id: 456, categoryId: Category.L1P10, englishWord: 'Parents', koreanWord: '부모님', chineseWord: '父母' },
    { id: 457, categoryId: Category.L1P10, englishWord: 'High school student', koreanWord: '고등학생', chineseWord: '高中生' },
    { id: 458, categoryId: Category.L1P11, englishWord: 'To give', koreanWord: '주다', chineseWord: '给' },
    { id: 459, categoryId: Category.L1P11, englishWord: 'To send', koreanWord: '보내다', chineseWord: '发送' },
    { id: 460, categoryId: Category.L1P11, englishWord: 'To receive', koreanWord: '받다', chineseWord: '收到' },
    { id: 461, categoryId: Category.L1P11, englishWord: 'Gift', koreanWord: '선물', chineseWord: '礼物' },
    { id: 462, categoryId: Category.L1P11, englishWord: 'Invitation', koreanWord: '초대', chineseWord: '邀请' },
    { id: 463, categoryId: Category.L1P11, englishWord: 'Invitation card', koreanWord: '초대장', chineseWord: '邀请函' },
    { id: 464, categoryId: Category.L1P11, englishWord: 'Parents\' Day', koreanWord: '어버이날', chineseWord: '父母节' },
    { id: 465, categoryId: Category.L1P11, englishWord: 'Teacher\'s Day', koreanWord: '스승의 날', chineseWord: '教师节' },
    { id: 466, categoryId: Category.L1P11, englishWord: 'Graduation ceremony', koreanWord: '졸업식', chineseWord: '毕业典礼' },
    { id: 467, categoryId: Category.L1P11, englishWord: 'Wedding', koreanWord: '결혼식', chineseWord: '婚礼' },
    { id: 468, categoryId: Category.L1P11, englishWord: 'To congratulate', koreanWord: '축하하다', chineseWord: '祝贺' },
    { id: 469, categoryId: Category.L1P11, englishWord: 'To use a card', koreanWord: '카드를 쓰다', chineseWord: '用卡' },
    { id: 470, categoryId: Category.L1P11, englishWord: 'To sing a song', koreanWord: '노래를 부르다', chineseWord: '唱歌' },
    { id: 471, categoryId: Category.L1P11, englishWord: 'Cake', koreanWord: '케이크', chineseWord: '蛋糕' },
    { id: 472, categoryId: Category.L1P11, englishWord: 'Women\'s Day', koreanWord: '여성의 날', chineseWord: '妇女节' },
    { id: 473, categoryId: Category.L1P11, englishWord: 'Children\'s Day', koreanWord: '어린이날', chineseWord: '儿童节' },
    { id: 474, categoryId: Category.L1P11, englishWord: 'To feel good', koreanWord: '기분이 좋다', chineseWord: '感觉很好' },
    { id: 475, categoryId: Category.L1P11, englishWord: 'Bouquet', koreanWord: '꽃다발', chineseWord: '花束' },
    { id: 476, categoryId: Category.L1P11, englishWord: 'To make a call', koreanWord: '전화를 하다', chineseWord: '拨打电话' },
    { id: 477, categoryId: Category.L1P11, englishWord: 'To receive a call', koreanWord: '전화를 받다', chineseWord: '接电话' },
    {
      id: 478,
      categoryId: Category.L1P12,
      englishWord: 'Holiday',
      koreanWord: '휴일',
      chineseWord: '假日'
    },
    {
      id: 479,
      categoryId: Category.L1P12,
      englishWord: 'Play basketball at the park',
      koreanWord: '공원에서 농구를 하다',
      chineseWord: '在公园打篮球'
    },
    {
      id: 480,
      categoryId: Category.L1P12,
      englishWord: 'Play computer games',
      koreanWord: '컴퓨터 게임을 하다',
      chineseWord: '玩电脑游戏'
    },
    {
      id: 481,
      categoryId: Category.L1P12,
      englishWord: 'Go on a trip',
      koreanWord: '여행을 가다',
      chineseWord: '去旅行'
    },
    {
      id: 482,
      categoryId: Category.L1P12,
      englishWord: 'Dine out with family',
      koreanWord: '가족하고 외식하다',
      chineseWord: '和家人外出就餐'
    },
    {
      id: 483,
      categoryId: Category.L1P12,
      englishWord: 'Go to an amusement park with children',
      koreanWord: '아이하고 놀이공원에 가다',
      chineseWord: '带孩子去游乐园'
    },
    {
      id: 484,
      categoryId: Category.L1P12,
      englishWord: 'Study Korean hard',
      koreanWord: '한국어를 열심히 공부하다',
      chineseWord: '努力学习韩语'
    },
    {
      id: 485,
      categoryId: Category.L1P12,
      englishWord: 'Learn Korean cooking',
      koreanWord: '한국 요리를 배우다',
      chineseWord: '学做韩国菜'
    },
    {
      id: 486,
      categoryId: Category.L1P12,
      englishWord: 'Take a nap',
      koreanWord: '낮잠을 자다',
      chineseWord: '午睡'
    },
    {
      id: 487,
      categoryId: Category.L1P12,
      englishWord: 'Go to a friend\'s house to play',
      koreanWord: '친구 집에 놀러 가다',
      chineseWord: '去朋友家玩'
    },
    {
      id: 488,
      categoryId: Category.L1P12,
      englishWord: 'Cultural center',
      koreanWord: '문화 센터',
      chineseWord: '文化中心'
    },
    {
      id: 489,
      categoryId: Category.L1P12,
      englishWord: 'Vacation',
      koreanWord: '휴가',
      chineseWord: '假期'
    },
    {
      id: 490,
      categoryId: Category.L1P12,
      englishWord: 'Swimming',
      koreanWord: '수영을 하다',
      chineseWord: '游泳'
    },
    {
      id: 491,
      categoryId: Category.L1P12,
      englishWord: 'Ride a boat',
      koreanWord: '배를 타다',
      chineseWord: '乘船'
    },
    {
      id: 492,
      categoryId: Category.L1P12,
      englishWord: 'Go fishing (in the sea)',
      koreanWord: '(바다) 낚시를 하다',
      chineseWord: '海钓'
    },
    {
      id: 493,
      categoryId: Category.L1P12,
      englishWord: 'Hiking',
      koreanWord: '등산을 하다',
      chineseWord: '登山'
    },
    {
      id: 494,
      categoryId: Category.L1P12,
      englishWord: 'Camping',
      koreanWord: '캠핑을 하다',
      chineseWord: '露营'
    },
    {
      id: 495,
      categoryId: Category.L1P12,
      englishWord: 'Floral arrangement',
      koreanWord: '꽃꽂이를 하다',
      chineseWord: '插花'
    },
    {
      id: 496,
      categoryId: Category.L1P12,
      englishWord: 'Care for animals',
      koreanWord: '동물을 구경하다',
      chineseWord: '照顾动物'
    },
    {
      id: 497,
      categoryId: Category.L1P12,
      englishWord: 'Ride a roller coaster',
      koreanWord: '놀이 기구를 타다',
      chineseWord: '坐过山车'
    },
    {
      id: 498,
      categoryId: Category.L1P12,
      englishWord: 'Watch fireworks',
      koreanWord: '불꽃놀이를 보다',
      chineseWord: '看烟花'
    },
    {
      id: 499,
      categoryId: Category.L1P12,
      englishWord: 'Meet hometown friends',
      koreanWord: '고향 친구들을 만나다',
      chineseWord: '见老朋友'
    },
    {
      id: 500,
      categoryId: Category.L1P12,
      englishWord: 'Meet parents',
      koreanWord: '부모님을 만나다',
      chineseWord: '见父母'
    },
    {
      id: 501,
      categoryId: Category.L1P12,
      englishWord: 'Eat hometown food',
      koreanWord: '고향 음식을 먹다',
      chineseWord: '吃家乡的食物'
    },
    {
      id: 502,
      categoryId: Category.L1P12,
      englishWord: 'Ginseng tea',
      koreanWord: '인삼차',
      chineseWord: '人参茶'
    },
    {
      id: 503,
      categoryId: Category.L1P12,
      englishWord: 'Cosmetics',
      koreanWord: '화장품',
      chineseWord: '化妆品'
    },
    {
      id: 504,
      categoryId: Category.L1P12,
      englishWord: 'Relatives',
      koreanWord: '친척',
      chineseWord: '亲戚'
    },
    {
      id: 505,
      categoryId: Category.L1P12,
      englishWord: 'Quickly',
      koreanWord: '빨리',
      chineseWord: '快点'
    },
    {
      id: 506,
      categoryId: Category.L1P12,
      englishWord: 'Ansan',
      koreanWord: '안산',
      chineseWord: '安山'
    }
];

export interface Verbs {
  id: number;
  englishWord: string;
  koreanWord: string;
  chineseWord: string;
  declarativePresent: string;
  declarativePast: string;
  declarativeFuture: string;
  inquisitivePast: string;
  imperative: string;
  wantTo: string;
  connectiveAnd: string;
}

export interface VerbForm {
  id: number;
  formName: string;
  key: keyof Verbs;
}

export const verbForms: VerbForm[] = [
  { id: 1, formName: 'Declarative Present', key: 'declarativePresent' },
  { id: 2, formName: 'Declarative Past', key: 'declarativePast' },
  { id: 3, formName: 'Declarative Future', key: 'declarativeFuture' },
  { id: 4, formName: 'Inquisitive Past', key: 'inquisitivePast' },
  { id: 5, formName: 'Imperative', key: 'imperative' },
  { id: 6, formName: 'Want to', key: 'wantTo' },
  { id: 7, formName: 'Connective And', key: 'connectiveAnd' }
];

export const verbsList: Verbs[] = [
  {
    id: 1,
    englishWord: 'write',
    koreanWord: '쓰다',
    chineseWord: '写',
    declarativePresent: '써요',
    declarativePast: '썼어요',
    declarativeFuture: '쓸 거예요',
    inquisitivePast: '썼나요',
    imperative: '쓰세요',
    wantTo: '쓰고 싶어요',
    connectiveAnd: '쓰고'
  },
  {
    id: 2,
    englishWord: 'rest',
    koreanWord: '쉬다',
    chineseWord: '休息',
    declarativePresent: '쉬어요',
    declarativePast: '쉬었어요',
    declarativeFuture: '쉴 거예요',
    inquisitivePast: '쉬었나요',
    imperative: '쉬세요',
    wantTo: '쉬고 싶어요',
    connectiveAnd: '쉬고'
  },
  {
    id: 3,
    englishWord: 'watch',
    koreanWord: '보다',
    chineseWord: '看',
    declarativePresent: '봐요',
    declarativePast: '봤어요',
    declarativeFuture: '볼 거예요',
    inquisitivePast: '봤나요',
    imperative: '보세요',
    wantTo: '보고 싶어요',
    connectiveAnd: '보고'
  },
  {
    id: 4,
    englishWord: 'study',
    koreanWord: '공부하다',
    chineseWord: '学习',
    declarativePresent: '공부해요',
    declarativePast: '공부했어요',
    declarativeFuture: '공부할 거예요',
    inquisitivePast: '공부했나요',
    imperative: '공부하세요',
    wantTo: '공부하고 싶어요',
    connectiveAnd: '공부하고'
  },
  {
    id: 5,
    englishWord: 'cook',
    koreanWord: '요리하다',
    chineseWord: '做饭',
    declarativePresent: '요리해요',
    declarativePast: '요리했어요',
    declarativeFuture: '요리할 거예요',
    inquisitivePast: '요리했나요',
    imperative: '요리하세요',
    wantTo: '요리하고 싶어요',
    connectiveAnd: '요리하고'
  },
  {
    id: 6,
    englishWord: 'eat',
    koreanWord: '먹다',
    chineseWord: '吃',
    declarativePresent: '먹어요',
    declarativePast: '먹었어요',
    declarativeFuture: '먹을 거예요',
    inquisitivePast: '먹었나요',
    imperative: '드세요',
    wantTo: '먹고 싶어요',
    connectiveAnd: '먹고'
  },
  {
    id: 7,
    englishWord: 'meet',
    koreanWord: '만나다',
    chineseWord: '见面',
    declarativePresent: '만나요',
    declarativePast: '만났어요',
    declarativeFuture: '만날 거예요',
    inquisitivePast: '만났나요',
    imperative: '만나세요',
    wantTo: '만나고 싶어요',
    connectiveAnd: '만나고'
  },
  {
    id: 8,
    englishWord: 'buy',
    koreanWord: '사다',
    chineseWord: '买',
    declarativePresent: '사요',
    declarativePast: '샀어요',
    declarativeFuture: '살 거예요',
    inquisitivePast: '샀나요',
    imperative: '사세요',
    wantTo: '사고 싶어요',
    connectiveAnd: '사고'
  },
  {
    id: 9,
    englishWord: 'work',
    koreanWord: '일하다',
    chineseWord: '工作',
    declarativePresent: '일해요',
    declarativePast: '일했어요',
    declarativeFuture: '일할 거예요',
    inquisitivePast: '일했나요',
    imperative: '일하세요',
    wantTo: '일하고 싶어요',
    connectiveAnd: '일하고'
  },
  {
    id: 10,
    englishWord: 'sleep',
    koreanWord: '자다',
    chineseWord: '睡觉',
    declarativePresent: '자요',
    declarativePast: '잤어요',
    declarativeFuture: '잘 거예요',
    inquisitivePast: '잤나요',
    imperative: '주무세요',
    wantTo: '자고 싶어요',
    connectiveAnd: '자고'
  },
  {
    id: 11,
    englishWord: 'exercise',
    koreanWord: '운동하다',
    chineseWord: '锻炼',
    declarativePresent: '운동해요',
    declarativePast: '운동했어요',
    declarativeFuture: '운동할 거예요',
    inquisitivePast: '운동했나요',
    imperative: '운동하세요',
    wantTo: '운동하고 싶어요',
    connectiveAnd: '운동하고'
  },
  {
    id: 12,
    englishWord: 'learn',
    koreanWord: '배우다',
    chineseWord: '学习',
    declarativePresent: '배워요',
    declarativePast: '배웠어요',
    declarativeFuture: '배울 거예요',
    inquisitivePast: '배웠나요',
    imperative: '배우세요',
    wantTo: '배우고 싶어요',
    connectiveAnd: '배우고'
  },
  {
    id: 13,
    englishWord: 'wash',
    koreanWord: '씻다',
    chineseWord: '洗',
    declarativePresent: '씻어요',
    declarativePast: '씻었어요',
    declarativeFuture: '씻을 거예요',
    inquisitivePast: '씻었나요',
    imperative: '씻으세요',
    wantTo: '씻고 싶어요',
    connectiveAnd: '씻고'
  },
  {
    id: 14,
    englishWord: 'put on clothes',
    koreanWord: '옷을 입다',
    chineseWord: '穿衣服',
    declarativePresent: '옷을 입어요',
    declarativePast: '옷을 입었어요',
    declarativeFuture: '옷을 입을 거예요',
    inquisitivePast: '옷을 입었나요',
    imperative: '옷을 입으세요',
    wantTo: '옷을 입고 싶어요',
    connectiveAnd: '옷을 입고'
  },
  {
    id: 15,
    englishWord: 'order',
    koreanWord: '주문하다',
    chineseWord: '点菜',
    declarativePresent: '주문해요',
    declarativePast: '주문했어요',
    declarativeFuture: '주문할 거예요',
    inquisitivePast: '주문했나요',
    imperative: '주문하세요',
    wantTo: '주문하고 싶어요',
    connectiveAnd: '주문하고'
  },
  {
    id: 16,
    englishWord: 'clean',
    koreanWord: '청소하다',
    chineseWord: '打扫',
    declarativePresent: '청소해요',
    declarativePast: '청소했어요',
    declarativeFuture: '청소할 거예요',
    inquisitivePast: '청소했나요',
    imperative: '청소하세요',
    wantTo: '청소하고 싶어요',
    connectiveAnd: '청소하고'
  },
  {
    id: 17,
    englishWord: 'play',
    koreanWord: '놀다',
    chineseWord: '玩',
    declarativePresent: '놀아요',
    declarativePast: '놀았어요',
    declarativeFuture: '놀 거예요',
    inquisitivePast: '놀았나요',
    imperative: '노세요',
    wantTo: '놀고 싶어요',
    connectiveAnd: '놀고'
  },
  {
    id: 18,
    englishWord: 'drink',
    koreanWord: '마시다',
    chineseWord: '喝',
    declarativePresent: '마셔요',
    declarativePast: '마셨어요',
    declarativeFuture: '마실 거예요',
    inquisitivePast: '마셨어요',
    imperative: '드세요',
    wantTo: '마시고 싶어요',
    connectiveAnd: '마시고'
  },
  {
    id: 19,
    englishWord: 'give',
    koreanWord: '주다',
    chineseWord: '给',
    declarativePresent: '줘요',
    declarativePast: '줬어요',
    declarativeFuture: '줄 거예요',
    inquisitivePast: '줬어요',
    imperative: '주세요',
    wantTo: '주고 싶어요',
    connectiveAnd: '주고'
  },
  {
    id: 20,
    englishWord: 'send',
    koreanWord: '보내다',
    chineseWord: '发送',
    declarativePresent: '보내요',
    declarativePast: '보냈어요',
    declarativeFuture: '보낼 거예요',
    inquisitivePast: '보냈어요',
    imperative: '보내세요',
    wantTo: '보내고 싶어요',
    connectiveAnd: '보내고'
  },
  {
    id: 21,
    englishWord: 'receive',
    koreanWord: '받다',
    chineseWord: '接收',
    declarativePresent: '받아요',
    declarativePast: '받았어요',
    declarativeFuture: '받을 거예요',
    inquisitivePast: '받았어요',
    imperative: '받으세요',
    wantTo: '받고 싶어요',
    connectiveAnd: '받고'
  },
  {
    id: 22,
    englishWord: 'invite',
    koreanWord: '초대하다',
    chineseWord: '邀请',
    declarativePresent: '초대해요',
    declarativePast: '초대했어요',
    declarativeFuture: '초대할 거예요',
    inquisitivePast: '초대했어요',
    imperative: '초대하세요',
    wantTo: '초대하고 싶어요',
    connectiveAnd: '초대하고'
  },
  {
    id: 23,
    englishWord: 'congratulate',
    koreanWord: '축하하다',
    chineseWord: '祝贺',
    declarativePresent: '축하해요',
    declarativePast: '축하했어요',
    declarativeFuture: '축하할 거예요',
    inquisitivePast: '축하했어요',
    imperative: '축하하세요',
    wantTo: '축하하고 싶어요',
    connectiveAnd: '축하하고'
  },
  {
    id: 24,
    englishWord: 'sing',
    koreanWord: '노래를 부르다',
    chineseWord: '唱歌',
    declarativePresent: '노래를 불러요',
    declarativePast: '노래를 불렀어요',
    declarativeFuture: '노래를 부를 거예요',
    inquisitivePast: '노래를 불렀어요',
    imperative: '노래를 부르세요',
    wantTo: '노래를 부르고 싶어요',
    connectiveAnd: '노래를 부르고'
  }
];

